// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeejeuokfrndzwhkkyez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplZWpldW9rZnJuZHp3aGtreWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNTkzMTQsImV4cCI6MjA1ODkzNTMxNH0.tyMtzThIqYiusbPjGg5Y0lPobFgQSRXM6MKjXnS5dWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);